# Generated by Django 5.2.2 on 2025-06-08 13:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(db_column='InvoiceId', primary_key=True, serialize=False)),
                ('invoice_date', models.DateTimeField(db_column='InvoiceDate', verbose_name='birth date')),
                ('billing_address', models.CharField(blank=True, db_column='BillingAddress', max_length=255, null=True, verbose_name='billing address')),
                ('billing_city', models.CharField(blank=True, db_column='BillingCity', max_length=128, null=True, verbose_name='billing city')),
                ('billing_state', models.CharField(blank=True, db_column='BillingState', max_length=128, null=True, verbose_name='billing state')),
                ('billing_country', models.CharField(blank=True, db_column='BillingCountry', max_length=64, null=True, verbose_name='billing country')),
                ('billing_postal_code', models.CharField(blank=True, db_column='BillingPostalCode', max_length=20, null=True, verbose_name='billing postal code')),
                ('total', models.DecimalField(db_column='Total', decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='total')),
                ('customer', models.ForeignKey(blank=True, db_column='CustomerId', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='customers.customer')),
            ],
            options={
                'verbose_name': 'invoice',
                'verbose_name_plural': 'invoices',
                'db_table': 'Invoice',
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.AutoField(db_column='InvoiceLineId', primary_key=True, serialize=False)),
                ('unit_price', models.DecimalField(db_column='UnitPrice', decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='price')),
                ('quantity', models.PositiveIntegerField(db_column='Quantity', verbose_name='quantity')),
                ('invoice', models.ForeignKey(db_column='InvoiceId', on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='sales.invoice')),
                ('track', models.ForeignKey(db_column='TrackId', on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='music.track')),
            ],
            options={
                'verbose_name': 'invoice line',
                'verbose_name_plural': 'invoice lines',
                'db_table': 'InvoiceLine',
                'ordering': ['id'],
            },
        ),
    ]
