# Generated by Django 5.2.2 on 2025-06-08 13:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(db_column='CustomerId', primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='FirstName', max_length=64, verbose_name='first name')),
                ('last_name', models.CharField(db_column='LastName', max_length=64, verbose_name='last name')),
                ('company', models.CharField(blank=True, db_column='Company', max_length=128, null=True, verbose_name='company')),
                ('address', models.CharField(blank=True, db_column='Address', max_length=255, null=True, verbose_name='address')),
                ('city', models.CharField(db_column='City', max_length=128, verbose_name='city')),
                ('state', models.CharField(db_column='State', max_length=128, verbose_name='state')),
                ('country', models.CharField(db_column='Country', max_length=64, verbose_name='country')),
                ('postal_code', models.CharField(blank=True, db_column='PostalCode', max_length=20, null=True, verbose_name='postal code')),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=32, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number. Allowed characters: optional leading +, digits, spaces, parentheses, and dashes.', regex='\\A\\+?[\\d \\-\\(\\)]+\\Z'), django.core.validators.MinLengthValidator(6, message='Phone number must be at least 6 characters long.')], verbose_name='phone number')),
                ('fax', models.CharField(blank=True, db_column='Fax', max_length=32, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number. Allowed characters: optional leading +, digits, spaces, parentheses, and dashes.', regex='\\A\\+?[\\d \\-\\(\\)]+\\Z'), django.core.validators.MinLengthValidator(6, message='Phone number must be at least 6 characters long.')], verbose_name='fax')),
                ('email', models.EmailField(blank=True, db_column='Email', max_length=254, null=True, unique=True, verbose_name='email')),
                ('support_representative', models.ForeignKey(blank=True, db_column='SupportRepId', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='employees.employee', verbose_name='support representative')),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
                'db_table': 'Customer',
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
