# Generated by Django 5.2.2 on 2025-06-08 13:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(db_column='ArtistId', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=128, verbose_name='name')),
            ],
            options={
                'verbose_name': 'artist',
                'verbose_name_plural': 'artists',
                'db_table': 'Artist',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(db_column='GenreId', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=128, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'genre',
                'verbose_name_plural': 'genres',
                'db_table': 'Genre',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.AutoField(db_column='MediaTypeId', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=128, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'media type',
                'verbose_name_plural': 'media types',
                'db_table': 'MediaType',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(db_column='AlbumId', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=128, verbose_name='title')),
                ('artist', models.ForeignKey(db_column='ArtistId', on_delete=django.db.models.deletion.PROTECT, related_name='albums', to='music.artist', verbose_name='artist')),
            ],
            options={
                'verbose_name': 'album',
                'verbose_name_plural': 'albums',
                'db_table': 'Album',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(db_column='TrackId', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255, verbose_name='name')),
                ('composer', models.CharField(db_column='Composer', max_length=128, verbose_name='composer')),
                ('milliseconds', models.PositiveIntegerField(db_column='Milliseconds', verbose_name='duration')),
                ('bytes', models.PositiveIntegerField(db_column='Bytes', verbose_name='size')),
                ('unit_price', models.DecimalField(db_column='UnitPrice', decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='price')),
                ('album', models.ForeignKey(db_column='AlbumId', on_delete=django.db.models.deletion.PROTECT, related_name='tracks', to='music.album')),
                ('genre', models.ForeignKey(db_column='GenreId', on_delete=django.db.models.deletion.PROTECT, related_name='tracks', to='music.genre')),
                ('media_type', models.ForeignKey(db_column='MediaTypeId', on_delete=django.db.models.deletion.PROTECT, related_name='tracks', to='music.mediatype')),
            ],
            options={
                'verbose_name': 'track',
                'verbose_name_plural': 'tracks',
                'db_table': 'Track',
                'ordering': ['name'],
            },
        ),
    ]
