# Generated by Django 5.2.2 on 2025-06-08 13:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(db_column='EmployeeId', primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='FirstName', max_length=64, verbose_name='first name')),
                ('last_name', models.CharField(db_column='LastName', max_length=64, verbose_name='last name')),
                ('title', models.CharField(db_column='Title', max_length=255, verbose_name='title')),
                ('birthdate', models.DateTimeField(blank=True, db_column='BirthDate', null=True, verbose_name='birth date')),
                ('hire_date', models.DateTimeField(db_column='HireDate', verbose_name='hire date')),
                ('address', models.CharField(db_column='Address', max_length=255, verbose_name='address')),
                ('city', models.CharField(db_column='City', max_length=128, verbose_name='city')),
                ('state', models.CharField(db_column='State', max_length=128, verbose_name='state')),
                ('country', models.CharField(db_column='Country', max_length=64, verbose_name='country')),
                ('postal_code', models.CharField(db_column='PostalCode', max_length=20, verbose_name='postal code')),
                ('phone', models.CharField(db_column='Phone', max_length=32, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number. Allowed characters: optional leading +, digits, spaces, parentheses, and dashes.', regex='\\A\\+?[\\d \\-\\(\\)]+\\Z'), django.core.validators.MinLengthValidator(6, message='Phone number must be at least 6 characters long.')], verbose_name='phone number')),
                ('fax', models.CharField(blank=True, db_column='Fax', max_length=32, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number. Allowed characters: optional leading +, digits, spaces, parentheses, and dashes.', regex='\\A\\+?[\\d \\-\\(\\)]+\\Z'), django.core.validators.MinLengthValidator(6, message='Phone number must be at least 6 characters long.')], verbose_name='fax')),
                ('email', models.EmailField(db_column='Email', max_length=254, unique=True, verbose_name='email')),
                ('reports_to', models.ForeignKey(blank=True, db_column='ReportsTo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='employees.employee', verbose_name='reports to')),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
                'db_table': 'Employee',
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
